# Generated by Django 5.0.1 on 2024-01-24 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing', models.DateTimeField(auto_now=True, verbose_name='Дата последней рассылки')),
                ('status', models.CharField(blank=True, max_length=60, null=True, verbose_name='Статус отправки')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование рассылки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Вреия начала рассылки')),
                ('second_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Врея следующей рассылки')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время окончания рассылки')),
                ('interval', models.CharField(choices=[('Разово', 'Разово'), ('Ежедневно', 'Ежедневно'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='разовая', max_length=60, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], help_text='Создана или Завершена', max_length=60, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
