# Generated by Django 5.0.1 on 2024-01-19 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('star_date',), 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='Инкогнито', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец клиента'),
        ),
        migrations.AddField(
            model_name='logs',
            name='last_mailing',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней рассылки'),
        ),
        migrations.AddField(
            model_name='logs',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
        ),
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Статус отправки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='interval',
            field=models.CharField(choices=[('Разово', 'Разово'), ('Ежедневно', 'Ежедневно'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='разовая', max_length=60, verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='mail_to',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Кому'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='Без названия', max_length=100, verbose_name='Наименование рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CСоздатель рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='second_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Врея следующей рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='star_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Вреия начала рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='В процессе', help_text='Создана или Завершена', max_length=60, verbose_name='Статус рассылки'),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='Ты не знаешь, кто я, но я знаю тебя. Давай сыграем в игру...', verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='Привет!', max_length=250, verbose_name='Тема письма'),
        ),
    ]
