# Generated by Django 5.0.1 on 2024-01-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='Текст отсутствует', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/preview/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='blog',
            name='public_date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Заголовок отсутствует', max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='blog',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
